### ISSUE TITLE
Garage & Lock

### ISSUE THREAD

**Issue by iondarie** [danilkorotkov/esp32-gate-HomeSpan#1]
Thank you so much for your answer in https://github.com/HomeSpan/HomeSpan/discussions/102

I am now trying to use your code but i have run into some issues, the sensors are bouncing like crazy and i was wondering if the sensors can be debounced via software or only hardware ?

```
23:36:03.010 -> closed by timeout
23:36:03.010 -> ----------ClSensorPin.SENSOR_RELEASED----------
23:36:09.597 -> ----------ClSensorPin.SENSOR_CLOSED----------
23:36:16.269 -> ----------ClSensorPin.SENSOR_RELEASED----------
23:36:22.367 -> opened by timeout
23:36:22.367 -> ----------ClSensorPin.SENSOR_CLOSED----------
23:36:28.511 -> opened by timeout
23:36:28.511 -> ----------ClSensorPin.SENSOR_RELEASED----------
23:36:30.150 -> ----------OpSensorPin.SENSOR_RELEASED----------
23:36:35.675 -> ----------OpSensorPin.SENSOR_CLOSED----------
23:36:35.708 -> ----------ClSensorPin.SENSOR_CLOSED----------
23:36:47.430 -> ----------ClSensorPin.SENSOR_RELEASED----------
23:36:47.430 -> opened by timeout
23:36:47.430 -> ----------ClSensorPin.SENSOR_CLOSED----------
23:36:53.716 -> ----------ClSensorPin.SENSOR_RELEASED----------
23:36:59.357 -> ----------ClSensorPin.SENSOR_CLOSED----------
23:37:04.954 -> opened by timeout
23:37:06.364 -> ----------ClSensorPin.SENSOR_RELEASED----------
23:37:18.275 -> ----------ClSensorPin.SENSOR_CLOSED----------
23:37:18.275 -> --
```

Also can the obstruction sensor be deleted/disabled withouth affecting the functionality of the garage door?

Thank you,

**Comment by danilkorotkov** [comment]
If nothing connected to ob sensor input - sensor always “disabled”
Check your circuit. My limit sensors connected this way- diode, 10-47uF capacitor to ground, lm317 as current limit to 20ma and optocoupler at the end. Capacitor is debouncing high freq. also software ignores sensor changes after interrupt was detected (PortPollTimeout)

**Comment by danilkorotkov** [comment]
![D86DEA7F-F5B4-4FB0-869F-39087F98A890](https://user-images.githubusercontent.com/25537053/123559215-5d4e8480-d7a3-11eb-8b58-ceaec2f449f6.jpeg)

**Comment by danilkorotkov** [comment]
Of course, ground before optocoupler and ground after it is not the same.

**Comment by danilkorotkov** [comment]
Closed?
